### ISSUE TITLE
Not working with esbuild

### ISSUE THREAD

**Issue by FabianDaniel00** [janosh/svelte-multiselect#296]
We have an older application and we are building it with esbuild. We want to integrate Svelte into it; we are using the [esbuild-svelte](https://www.npmjs.com/package/esbuild-svelte) plugin.

## Repro

Steps to reproduce the problem:

- When trying to import `svelte-multiselect`, I got the following error from esbuild:

```bash
✘ [ERROR] Could not resolve "svelte/internal/flags/legacy"

    admin_ui/node_modules/svelte-multiselect/dist/icons/Cross.svelte:2:7:
      2 │ import "svelte/internal/flags/legacy";
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./internal/flags/legacy" is not exported by package "svelte":

    admin_ui/node_modules/svelte-multiselect/node_modules/svelte/package.json:25:13:
      25 │   "exports": {
         ╵              ^

  You can mark the path "svelte/internal/flags/legacy" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
...
...
...
✘ [ERROR] Could not resolve "svelte/internal/client"

    admin_ui/node_modules/svelte-multiselect/dist/icons/Cross.svelte:3:19:
      3 │ import * as $ from "svelte/internal/client";
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./internal/client" is not exported by package "svelte":

    admin_ui/node_modules/svelte-multiselect/node_modules/svelte/package.json:25:13:
      25 │   "exports": {
         ╵              ^

  You can mark the path "svelte/internal/client" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

- Then I added the following to the esbuild config:
```js
{
  ...
  external: ['svelte/internal/client', 'svelte/internal/flags/legacy'],
  ...
}
```
And it got compiled successfully but I got the following error in the browser terminal:
```bash
Uncaught Error: Dynamic require of "svelte/internal/client" is not supported
```

## Expected behavior

It should build using esbuild.

## Additional context

Versions:
- `esbuild`: **0.24.0**
- `esbuild-svelte`: **0.9.0**
- `svelte-preprocess`: **6.0.3**
- `svelte`: **5.14.1**
- `svelte-multiselect`: **11.0.0-rc.1**

esbuild config:

```js
{
  entryPoints: [{ out: 'admin_ui', in: './admin_ui/src/main.ts' }],
  entryNames: '[ext]/[name]',
  assetNames: 'assets/[name]',
  target: 'es2020',
  bundle: true,
  color: true,
  outdir: path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    '..',
    'priv',
    'static'
  ),
  mainFields: ['svelte', 'browser', 'module', 'main'],
  conditions: ['svelte', 'browser'],
  external: ['svelte/internal/client', 'svelte/internal/flags/legacy'],
  plugins: [
    esbuildSvelte({
      preprocess: sveltePreprocess({
        postcss: {
          configFilePath: 'admin_ui/postcss.config.js',
          plugins: [tailwindcss(tailwindConfig), autoprefixer]
        }
      })
    })
  ]
}
```

**Comment by janosh** [comment]
i'm a bit out of the loop with the latest in the Svelte ecosystem right now. might be `"svelte/internal/flags/legacy"` was only added in Svelte 5. which version are you using? either way, i'm confused since [`Cross.svelte`](https://github.com/janosh/svelte-multiselect/blob/25dc09792ead94532a7bd8e236665d5da0e11229/src/lib/icons/Cross.svelte) doesn't import from `svelte` anyway so it's probably some kind of version mismatch

**Comment by FabianDaniel00** [comment]
There is the versions I'm using:

> Versions:
> - `esbuild`: **0.24.0**
> - `esbuild-svelte`: **0.9.0**
> - `svelte-preprocess`: **6.0.3**
> - `svelte`: **5.14.1**
> - `svelte-multiselect`: **11.0.0-rc.1**

**Comment by janosh** [comment]
in that case maybe try the latest Svelte v4 release to see if the error changes or disappears

**Comment by FabianDaniel00** [comment]
In `Svelte v4.2.19` it gets compiled successfully but I got the following error in the browser console when the component needs to be rendered:
```bash
Component.js:130 Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at init2 (Component.js:130:44)
    at new MultiSelect (MultiSelect.svelte:410:43)
    at create_fragment7 (App.svelte:9:44)
    at init (Component.js:148:34)
    at new App (App.svelte:6:14)
    at main.ts:4:1
    at main.ts:4:61
init2 @ Component.js:130
MultiSelect @ MultiSelect.svelte:410
create_fragment7 @ App.svelte:9
init @ Component.js:148
App @ App.svelte:6
(anonymous) @ main.ts:4
(anonymous) @ main.ts:4
```

I have a `main.ts` file which is calling the `App.svelte` component.

**main.ts**:
```js
import App from './App.svelte';
import './main.css';

new App({ target: document.getElementById('admin-ui-app')! });
```

**App.svelte**:
```svelte
<script lang="ts">
	import MultiSelect from 'svelte-multiselect';

	const ui_libs = [`Svelte`, `React`, `Vue`, `Angular`, `...`]

	let selected: any = [];
</script>

<MultiSelect bind:selected options={ui_libs} />
```

**Comment by janosh** [comment]
that sounds like it might be a config issue on your end. can you retrieve the line on which it fails from `Component.js:130:44` to see what object the `$$` is being accessed on?

**Comment by FabianDaniel00** [comment]
I don't have a `Component.js` file, it's from the Svelte source code: https://github.com/sveltejs/svelte/blob/6045028666ba6b19ab03571f123ea62fac95b642/packages/svelte/src/runtime/internal/Component.js#L130

**Comment by janosh** [comment]
i know, thanks for digging that up. i figured you could maybe command-click on the error message to get into your `node_modules` where the error originates.

in any case, sounds like the cause of `TypeError: Cannot read properties of undefined (reading '$$')` or maybe `esbuild` is that `document.getElementById('admin-ui-app')!` returns `null`

**Comment by FabianDaniel00** [comment]
I found out what was the problem. 🙏

I had to add:
```js
{
  ...
  alias: { svelte: 'svelte' },
  ...
}
```
to the esbuild config.

Thank you for your help.

**Comment by janosh** [comment]
glad you fixed it and thanks for reporting back! 👍 might help others who encounter the same issue
