### ISSUE TITLE
Latest svelte , tried to make same component from the README.

### ISSUE THREAD

**Issue by ceo** [janosh/svelte-multiselect#6]
```
bundles src/main.js → public/build/bundle.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-multiselect/MultiSelect.css (1:0)
1: .multiselect.svelte-19t1nlc.svelte-19t1nlc{position:relative;margin:1em 0;border:var(--sms-border, 1pt solid lightgray);border-radius:var(--sms-border-radius, 5pt);align-items:center;min-height:18pt;display:flex;cursor:text}.multiselect.svelte-19t1nlc.svelte-19t1nlc:focus-within{border:var(--sms-focus-border, 1pt solid var(--sms-active-color, cornflowerblue))}.multiselect.readonly.svelte-19t1nlc.svelte-19t1nlc{background:var(--sms-readonly-bg, lightgray)}ul.tokens.svelte-19t1nlc>li.svelte-19t1nlc{background:var(--sms-token-bg, var(--sms-active-color, cornflowerblue));align-items:center;border-radius:4pt;display:flex;margin:2pt;padding:0 0 0 1ex;transition:0.3s;white-space:nowrap;height:16pt}ul.tokens.svelte-19t1nlc>li button.svelte-19t1nlc,button.remove-all.svelte-19t1nlc.svelte-19t1nlc{align-items:center;border-radius:50%;display:flex;cursor:pointer;transition:0.2s}ul.tokens.svelte-19t1nlc>li button.svelte-19t1nlc:hover,button.remove-all.svelte-19t1nlc.svelte-19t1nlc:hover{color:var(--sms-remove-x-hover-color, lightgray)}button.svelte-19t1nlc.svelte-19t1nlc{color:inherit;background:transparent;border:none;cursor:pointer;outline:none;padding:0 2pt}.multiselect.svelte-19t1nlc input.svelte-19t1nlc{border:none;outline:none;background:none;box-shadow:none;color:var(--sms-text-color, inherit);flex:1;width:1pt}ul.tokens.svelte-19t1nlc.svelte-19t1nlc{display:flex;padding:0;margin:0;flex-wrap:wrap;flex:1}ul.options.svelte-19t1nlc.svelte-19t1nlc{list-style:none;max-height:50vh;padding:0;top:100%;width:100%;cursor:pointer;position:absolute;border-radius:1ex;overflow:auto;background:var(--sms-options-bg, white)}ul.options.hidden.svelte-19t1nlc.svelte-19t1nlc{visibility:hidden}ul.options.svelte-19t1nlc li.svelte-19t1nlc{padding:3pt 2ex}ul.options.svelte-19t1nlc li.selected.svelte-19t1nlc{border-left:var(
   ^
2:       --sms-li-selected-border-left,
3:       3pt solid var(--sms-selected-color, green)
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:5307:30)
    at Module.error (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:9716:16)
    at Module.tryParse (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:10122:25)
    at Module.setSource (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:10023:24)
    at ModuleLoader.addModuleSource (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:18337:20)
    at ModuleLoader.fetchModule (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:18393:9)
    at async Promise.all (index 6)
    at ModuleLoader.fetchStaticDependencies (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:18418:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/Users/macuser/Downloads/notus-svelte-main/node_modules/rollup/dist/shared/rollup.js:18395:9)


[2021-08-28 08:35:44] waiting for changes...
```

**Comment by janosh** [comment]
Could you provide a few more details of what you're doing? It looks like you're trying to bundle with pure Rollup? Is your error occurring in a non-SvelteKit project?

**Comment by janosh** [comment]
Closing as needs more info. Feel free to reopen with additional details.
